### ISSUE TITLE
App crashes on start up even though "BUILD SUCCESSFUL in 8s"

### ISSUE THREAD

**Issue by lchua2314** [cpp-css/frontEndFall2020#17]
"Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0."
The app crashes on start up for me and Peter.

**Comment by exelarios** [comment]
What are your guys Gradle's version?

A temporary fix would just be copying over your android and ios directories from your previous working build to the latest build for your local repository. I also experienced this problem whenever I fetch my changes from master. We might switch to Docker, if we can't resolve this issue by just standardizing our build versions.

**Comment by exelarios** [comment]
What are your guys Gradle's version?

**Comment by lchua2314** [comment]
I am using gradle version 3.5.3. This is the first time I had this issue. I also noticed you deleted the "package-lock.json" file. I'll try to recover that file and see if that works for the current master branch. Edit: That didn't work.

**Comment by exelarios** [comment]
Try to be in Gradle 6.3, because it's an updated version of it.

See what happens if you set your `android/gradle/wrapper/gradle-wrapper.properties` to what I have below.
```distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by lchua2314** [comment]
Mb. I was looking at the wrong place for the gradle version. It is 6.3. Edit: Also, I'm on Windows. Idk about Peter.

**Comment by exelarios** [comment]
Uhhh, we might need to set up Docker then. I haven't try to use docker before, so I'm not sure if it will fix the problem with the environment setup issues.

I honestly not sure if we should dockerize our project because it might complicate the project more. 🤔

**Comment by lchua2314** [comment]
I think we should get the other devs on the team to see if they can run the code. What OS are you using?

**Comment by exelarios** [comment]
I'm on MacOS

**Comment by lchua2314** [comment]
I'm on Windows.

**Comment by exelarios** [comment]
I doubt that's the issue though. 🤔

**Comment by lchua2314** [comment]
Hey, I got it to work. I had to clone the repo in a new file but it runs now.
