### ISSUE TITLE
Can't find variable: useContext

### ISSUE THREAD

**Issue by lchua2314** [cpp-css/frontEndFall2020#37]
When clicking on User Settings in the Profile tab I get this error:
"Can't find variable: useContext" on line 13 of UserSettings.component.js.
Not sure it's because of my workspace again or not. Everything else seems to work.

**Comment by exelarios** [comment]
My bad, I forgot to import useContext.
Just import useContext from react and you're good.
`import React, { useContext } from 'react';`
